name: parallel-rust
version: 0.1.0
homepage: https://github.com/morloclib/parallel-rust
synopsis: Rust (std::thread) implementations for the parallel module
description: Scoped-thread implementations of the parallel combinators.
category: control
license: MIT
author: "Zebulun Arendsee"
maintainer: "z@morloc.io"
github: https://github.com/morloclib/parallel-rust
bug-reports: https://github.com/morloclib/parallel-rust
